services:
  - type: worker
    name: zzbotfiche
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CSV_PATH
        value: ./data.csv
